// <auto-generated />
using System;
using Hostel_Manager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hostel_Manager.API.Migrations
{
    [DbContext(typeof(HostelDbContext))]
    [Migration("20231017085304_Update1")]
    partial class Update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hostel_Manager.API.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Vinh Long",
                            Detail = "So 19/23 Hem 4",
                            District = "Tam Binh",
                            Street = "Nguyen Trai",
                            Ward = "Song Phu"
                        },
                        new
                        {
                            Id = 2,
                            City = "Vinh Long",
                            Detail = "So 19/23 Hem 4",
                            District = "Tam Binh",
                            Street = "Nguyen Trai",
                            Ward = "Song Phu"
                        });
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Blog_Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Blog_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Blog_Image")
                        .HasColumnType("int");

                    b.Property<int>("Blog_Poster")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Blog_Image");

                    b.HasIndex("Blog_Poster");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Comment_Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Comment_Image")
                        .HasColumnType("int");

                    b.Property<int>("Comment_Poster")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Comment_Image");

                    b.HasIndex("Comment_Poster")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Hostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hostel_address")
                        .HasColumnType("int");

                    b.Property<string>("Hostel_discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hostel_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hostel_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Image_Hostel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<string>("Parking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hostel_address")
                        .IsUnique();

                    b.HasIndex("ImageId");

                    b.HasIndex("Owner");

                    b.ToTable("Hostels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = 2,
                            Create = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hostel_address = 1,
                            Hostel_discription = "Nha moi xay",
                            Hostel_name = "Nguyen Phat",
                            Hostel_phone = "0909033",
                            Image_Hostel = "/img/carousel-1.jpg",
                            Owner = 1,
                            Parking = "Co"
                        },
                        new
                        {
                            Id = 2,
                            Available = 2,
                            Create = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hostel_address = 2,
                            Hostel_discription = "Nha moi xay",
                            Hostel_name = "Nguyen Phat",
                            Hostel_phone = "09039039",
                            Image_Hostel = "/img/carousel-1.jpg",
                            Owner = 2,
                            Parking = "Co"
                        });
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("URL_Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            URL_Images = "/img/room-1.jpg"
                        });
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Electric")
                        .HasColumnType("real");

                    b.Property<int>("Hostel")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Room_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Water")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Hostel");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Hoanglong@gmail.com",
                            Password = "123456",
                            Phone = "090930239",
                            Username = "Long Hoang",
                            role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "Longvipzz@gmail.com",
                            Password = "123445",
                            Phone = "0930032",
                            Username = "Hoang Hoang",
                            role = 0
                        });
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Blog", b =>
                {
                    b.HasOne("Hostel_Manager.API.Entities.Image", "Images")
                        .WithMany("Blogs")
                        .HasForeignKey("Blog_Image")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hostel_Manager.API.Entities.User", "Users")
                        .WithMany("Blogs")
                        .HasForeignKey("Blog_Poster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Comment", b =>
                {
                    b.HasOne("Hostel_Manager.API.Entities.Image", "Images")
                        .WithMany("Comments")
                        .HasForeignKey("Comment_Image")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hostel_Manager.API.Entities.User", "Users")
                        .WithOne("Comments")
                        .HasForeignKey("Hostel_Manager.API.Entities.Comment", "Comment_Poster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Hostel", b =>
                {
                    b.HasOne("Hostel_Manager.API.Entities.Address", "Addresses")
                        .WithOne("Hostles")
                        .HasForeignKey("Hostel_Manager.API.Entities.Hostel", "Hostel_address")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hostel_Manager.API.Entities.Image", null)
                        .WithMany("Hostels")
                        .HasForeignKey("ImageId");

                    b.HasOne("Hostel_Manager.API.Entities.User", "Users")
                        .WithMany("Hostels")
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addresses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Room", b =>
                {
                    b.HasOne("Hostel_Manager.API.Entities.Hostel", "Hostels")
                        .WithMany("Rooms")
                        .HasForeignKey("Hostel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hostels");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Address", b =>
                {
                    b.Navigation("Hostles")
                        .IsRequired();
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Hostel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.Image", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Comments");

                    b.Navigation("Hostels");
                });

            modelBuilder.Entity("Hostel_Manager.API.Entities.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Comments")
                        .IsRequired();

                    b.Navigation("Hostels");
                });
#pragma warning restore 612, 618
        }
    }
}
